### ISSUE TITLE
list-table.xml suggestions

### ISSUE THREAD

**Issue by daobrien** [StyleGuides/english-for-techies#3]
Apart from ordered and itemized lists, are definition lists a separate category? e.g., in DocBook we use <variablelist> elements for this. You mention this later in key-value lists, but you use an itemized list.

"Use punctuation when a list item completes an introductory sentence."
- probably should be "use terminating punctuation"?
- or, does it mean *any* punctuation? e.g., "single words, sentence fragments, or short terms." This is a sentence fragment, but does it require a period because it also uses commas?

For the para that starts "Most of all, strive for consistency." I'd probably extend that a little. It's partly covered, but "if you have a list with a combination of complete sentences, sentence fragments, and single words, you should restructure the list." Something similar to that.

In the section about tense, the examples mostly start with "Students" instead of "you." If we're trying to push the 2nd-person active voice cart, we should set a good example. This also applies to using "since" to mean "because."

Can we add a section on parallelism in lists? I see many of examples of (e.g.), 
- use to specify the X variable
- specifies which value to apply to Y
- you can use this to change the config from the CLI

This also needs to be applied *across* lists, as well, especially in the same chapter and document. Not such a big deal if DO280 uses method X and JB318 uses method Y (better if they're the same), but within a book, they should be the same as much as possible.

**Comment by notklaatu** [comment]
Fixed in 626279c
